{% set name = "mkdocstrings-python-xref" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mkdocstrings_python_xref-{{ version }}.tar.gz
  sha256: f50b5d43fc6bf89c71d42f5366597b83646867ed5aaa461f4b6ac98728893b9c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - mkdocstrings-python >=1.6.2,<2.0

test:
  imports:
    - mkdocstrings_handlers.python_xref
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Enhanced mkdocstrings python handler
  home: https://github.com/analog-garage/mkdocstrings-python-xref
  doc_url: https://analog-garage.github.io/mkdocstrings-python-xref/
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - analog-cbarber
