{% set name = "mkdocstrings-python-xref" %}
{% set version = "1.6.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mkdocstrings_python_xref-{{ version }}.tar.gz
  sha256: ce26e37c58d3c4fad16aece914f4eec1795f1970282a9c219682d3590fdc10a1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - mkdocstrings-python >=1.6.2,<2.0

test:
  imports:
    - mkdocstrings_handlers.python_xref
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Enhanced mkdocstrings python handler
  home: https://github.com/analog-garage/mkdocstrings-python-xref
  doc_url: https://analog-garage.github.io/mkdocstrings-python-xref/
  license: Apache-2.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - analog-cbarber
